# Generated by Django 5.2.11 on 2026-02-18 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0005_box_cpu_gpu_motherboard_psu_ram_storage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PcBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.box')),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.cpu')),
                ('gpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.gpu')),
                ('motherboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.motherboard')),
                ('psu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.psu')),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.ram')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.storage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
